name: ferc1_eia_match
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<24
  - python>=3.11,<3.12
  - setuptools<69

  # Tricky binary dependencies, best resolved w/ conda:
  # - geopandas>=0.9,<0.11
  # - pygeos>=0.10,<0.13
  - python-snappy>=0.6,<1 # Ensures snappy-dev library gets installed
  # - numba>=0.56.1,<0.57 # not strictly necessary, but speeds some things up by 100x
  - sqlite>=3.36,<4 # Required by PUDL 0.5.0 and later.

  - nodejs # Useful for Jupyter and prettier pre-commit hook

  # Jupyter packages:
  - jupyterlab>=3.2,<3.7 # need to enforce 3.2 for splink, change later
  - nbconvert>=7,<8 # Used to clear notebook outputs in pre-commit hooks

  - seaborn>=0.12,<1.0

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,docs,tests,types]

variables:
  # fixes faiss search slowdown error
  OMP_WAIT_POLICY: "PASSIVE"
  OMP_NUM_THREADS: 1
