name: ferc_eia_match
channels:
  - conda-forge
  - defaults
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<23
  - python>=3.8,<3.12
  - setuptools<66

  # Tricky binary dependencies, best resolved w/ conda:
  # - geopandas>=0.9,<0.11
  # - pygeos>=0.10,<0.13
  - python-snappy>=0.6,<1 # Ensures snappy-dev library gets installed
  - numba>=0.55.1,<0.57 # not strictly necessary, but speeds some things up by 100x
  - sqlite>=3.36,<4 # Required by PUDL 0.5.0 and later.

  - pgmpy # move to setup later if used

  - nodejs # Useful for Jupyter and prettier pre-commit hook

  # Jupyter packages:
  - jupyterlab==3.2 # need to enforce 3.2 for splink, change later
  - nbconvert>=6,<7 # Used to clear notebook outputs in pre-commit hooks

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,docs,tests,types]
